## Task 1. Notebook structure

### BIKE-SHARING PLATFORM

1. Piotr Szeliga 235032
2. Julianna Mali 231572
3. Hubert Madej 231650

#### Bike sharing is when you want a bike and someone is able to to lend it to you.
#### That is what sharing means. It is about care and devotion to another human beings.
#### It is also about riding a bike. Is is also also a bike sharing platform

|<b>Advantages<b>|<b>Disadvantages<b>|
|--------------------|---------------------|
|You can get access to a bike when you need it|Someone can steal your bike|
|Get rid of your bike when you dont need it|The bike you borro might not be the colour you like |
|The platform is effective i guess|You need to interact socially to participate with other bikers|

## Task 2. Data loading and inspection

In [1]:
import pandas as pd
import numpy as np

In [3]:
bikes = pd.read_csv('bikes.csv')
payments = pd.read_csv('payments.csv')
rides = pd.read_csv('rides.csv')
stations = pd.read_csv('stations.csv')
users = pd.read_csv('users.csv')

In [7]:
dfs = [bikes, payments, rides, stations, users]

In [29]:
bikes.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   bike_id        20 non-null     int64
 1   bike_type      20 non-null     object
 2   purchase_year  20 non-null     int64
 3   status         20 non-null     object
dtypes: int64(2), object(2)
memory usage: 772.0+ bytes

        bike_id  purchase_year
count  20.00000      20.000000
mean   10.50000    2019.700000
std     5.91608       1.976174
min     1.00000    2017.000000
25%     5.75000    2018.000000
50%    10.50000    2019.500000
75%    15.25000    2021.000000
max    20.00000    2024.000000

In [31]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   bike_id        20 non-null     int64
 1   bike_type      20 non-null     object
 2   purchase_year  20 non-null     int64
 3   status         20 non-null     object
dtypes: int64(2), object(2)
memory usage: 772.0+ bytes

In [32]:
bikes.describe()

        bike_id  purchase_year
count  20.00000      20.000000
mean   10.50000    2019.700000
std     5.91608       1.976174
min     1.00000    2017.000000
25%     5.75000    2018.000000
50%    10.50000    2019.500000
75%    15.25000    2021.000000
max    20.00000    2024.000000

## Task 3. Data integration

In [33]:
merge1 = rides.merge(users, on='user_id')

In [35]:
merge2 = merge1.merge(bikes, on='bike_id')

In [38]:
merge3 = merge2.merge(payments, on='ride_id')

In [42]:
merge = pd.merge(merge3, stations, left_on='start_station', right_on='station_id').merge(stations, left_on='start_station', right_on='station_id')

In [43]:
merge

,ride_id,user_id,bike_id,start_station,end_station,duration_min,ride_date,name,user_type,city,...,amount_PLN,payment_type,station_id_x,station_name_x,district_x,capacity_x,station_id_y,station_name_y,district_y,capacity_y
0,1,8,7,6,2,17,2025-03-18,Anna Lee,student,London,...,8.30,subscription,6,Station 6,Podgorze,42,6,Station 6,Podgorze,42
1,2,14,6,8,3,22,2025-03-15,Robert Wilson,student,Warsaw,...,11.92,subscription,8,Station 8,Zwierzyniec,18,8,Station 8,Zwierzyniec,18
2,3,15,18,4,2,11,2025-03-02,Anna Hernandez,tourist,London,...,14.13,single,4,Station 4,Old Town,21,4,Station 4,Old Town,21
3,4,3,8,9,1,15,2025-03-14,Mark Wilson,tourist,Paris,...,14.75,subscription,9,Station 9,Zwierzyniec,21,9,Station 9,Zwierzyniec,21
4,5,28,13,8,4,8,2025-03-06,Alice Garcia,tourist,Vienna,...,6.98,single,8,Station 8,Zwierzyniec,18,8,Station 8,Zwierzyniec,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,15,18,8,4,14,2025-03-13,Anna Hernandez,tourist,London,...,3.69,subscription,8,Station 8,Zwierzyniec,18,8,Station 8,Zwierzyniec,18
146,147,17,5,4,10,60,2025-03-03,Emma Novak,tourist,Prague,...,14.44,subscription,4,Station 4,Old Town,21,4,Station 4,Old Town,21
147,148,11,17,5,7,22,2025-03-27,Daniel Clark,student,Vienna,...,10.71,subscription,5,Station 5,Zwierzyniec,42,5,Station 5,Zwierzyniec,42
148,149,24,10,1,5,58,2025-03-19,Julia Anderson,student,Berlin,...,13.36,promo,1,Station 1,Nowa Huta,45,1,Station 1,Nowa Huta,45
149,150,28,5,10,8,33,2025-03-18,Alice Garcia,tourist,Vienna,...,7.50,promo,10,Station 10,Old Town,40,10,Station 10,Old Town,40

In [48]:
final = merge[['name', 'user_type', 'bike_type', 'station_name_x', 'station_name_y', 'duration_min', 'amount_PLN']]

In [50]:
print(pd.concat([final.head(10), final.tail(10)]))

               name user_type bike_type station_name_x station_name_y  \
0          Anna Lee   student  electric      Station 6      Station 6
1     Robert Wilson   student  standard      Station 8      Station 8
2    Anna Hernandez   tourist  standard      Station 4      Station 4
3       Mark Wilson   tourist     cargo      Station 9      Station 9
4      Alice Garcia   tourist     cargo      Station 8      Station 8
5        Emma Smith   tourist  electric      Station 7      Station 7
6     Robert Wilson   student  standard      Station 8      Station 8
7        Anna Brown   student     cargo      Station 8      Station 8
8    Julia Anderson   student  standard      Station 1      Station 1
9         Piotr Lee   tourist  standard      Station 6      Station 6
140    Maria Garcia   regular  standard      Station 5      Station 5
141      Mark Nowak   tourist  standard     Station 10     Station 10
142   Robert Wilson   student  standard      Station 1      Station 1
143    Alice Wilson   student  electric      Station 2      Station 2
144      Mark Nowak   tourist  electric      Station 5      Station 5
145  Anna Hernandez   tourist  standard      Station 8      Station 8
146      Emma Novak   tourist  electric      Station 4      Station 4
147    Daniel Clark   student  standard      Station 5      Station 5
148  Julia Anderson   student     cargo      Station 1      Station 1
149    Alice Garcia   tourist  electric     Station 10     Station 10

     duration_min  amount_PLN
0              17        8.30
1              22       11.92
2              11       14.13
3              15       14.75
4               8        6.98
5              55        7.34
6              47        8.15
7              18        6.96
8               8       12.30
9              35        3.98
140            12        6.06
141            24       14.40
142            19        8.17
143            36        3.11
144            31       11.68
145            14        3.69
146            60       14.44
147            22       10.71
148            58       13.36
149            33        7.50

## Task 4. User activity analysis

In [128]:
final.groupby('name').aggregate({'user_type':'count','duration_min':'mean'}).rename(columns={'user_type':'ride count', 'duration_min':'average ride duration'}).sort_values(by='ride count', ascending=False).query("`ride count` >= 3")

                 ride count  average ride duration
name
Maria Clark              12              25.333333
Robert Wilson            10              30.900000
Daniel Clark              8              34.000000
Mark Wilson               7              24.857143
Alice Wilson              7              33.571429
Thomas Nowak              6              26.333333
Thomas Anderson           6              41.500000
Anna Hernandez            6              23.833333
Paul Brown                6              23.333333
Emma Clark                6              27.666667
Mark Nowak                6              43.666667
Olivia Lee                5              28.000000
Alice Garcia              5              31.400000
Anna Lee                  5              21.000000
Daniel Brown              5              25.800000
David Wilson              5              35.400000
Julia Hernandez           4              23.500000
Olivia Clark              4              44.500000
Anna Brown                4              30.250000
Piotr Lee                 4              18.750000
Olivia Brown              4              32.500000
Eva Martin                4              20.750000
Maria Garcia              4              26.750000
Julia Anderson            3              40.666667
Michael Lopez             3              43.666667
Mark Lopez                3              18.333333

## Task 5. Bike and station analysis

In [140]:
task5 = merge[['duration_min', 'bike_type', 'district_x']].groupby(by=['bike_type', 'district_x']).mean()
task5

                       duration_min
bike_type district_x
cargo     Bronowice       15.500000
          Kazimierz       33.666667
          Nowa Huta       54.500000
          Old Town        29.142857
          Podgorze        27.333333
          Zwierzyniec     24.692308
electric  Bronowice       42.750000
          Kazimierz       36.000000
          Nowa Huta       22.666667
          Old Town        35.266667
          Podgorze        34.000000
          Zwierzyniec     26.846154
standard  Bronowice       31.500000
          Kazimierz       19.333333
          Nowa Huta       29.444444
          Old Town        32.777778
          Podgorze        30.500000
          Zwierzyniec     27.740741